export const GET_DATA_FROM_FIREBASE = "GET_DATA_FROM_FIREBASE";
export const IS_LOADING = "IS_LOADING";
export const GET_SINGLE_BLOG_POST = "GET_SINGLE_BLOG_POST";
export const BUTTON_LOADING = "BUTTON_LOADING";
export const BUTTON_SUCCESS = "BUTTON_SUCCESS";
export const GET_COMMENTS = "GET_COMMENTS";
export const GET_BLOG_TOTAL = "GET_BLOG_TOTAL";

export const GET_CATEGORY = "GET_CATEGORY";

export const GET_SIDEBAR_DATA = "GET_SIDEBAR_DATA";
export const ADD_COUNTER = "ADD_COUNTER";
export const REDUCE_COUNTER = "REDUCE_COUNTER";
export const GET_SEARCH = "GET_SEARCH";
export const ADD_COMMENT = "ADD_COMMENT";
export const GET_RELATED_BLOGS = "GET_RELATED_BLOGS";
